blacklisted_words = [
    "fuck",
    "shit",
    "bitch",
    "fucker",
    "pussy",
    "asshole",
    "motherfucker",
    "ngentot",
    "anjing",
    "kontol",
    "tolol",
    "goblok",
    "bangsat"]


jokes_homok = [
    "Atmosfer bumi",
    "Kapal karam",
    "Lumpur lapindo blukutuk blukutuk",
    "Kabur",
    "Pak slapur main gendang jago banget rek",
    "Rudi 76 sedang di se kap dan d!s!ksa oleh psikopat",
    "Laba laba sunda",
    "Sekolah",
    "Minang kocak",
    "Tertangkap kamera zombie bandung",
    "Renang",
    "Recing ricko mandalika",
    "Fua'd motocross lok: gerobongan jawa tengah",
    "Si tukang atap",
    "Bermain air",
    "Meluncur",
    "Aku pergi", 
    "Aku kembali",
    "Dapa dibnh psikopat",
    "Kapten agung kapal-kapalan",
    "Pembudidayaan", 
    "Perkara sulit ini",
    "Slow aja keles",
    "Kamu lucu",
    "Meluncur",
    "Berjalan bersama mu dalam terik dan hujan",
    "Ketebak",
    "Banjarmasin slowmo",
    "Astmosfer bumi",
    "Gempa bumi",
    "Ku berlari terbang tinggi",
    "Panjat pinang",
    "Ular garaga milik Panji lepas waspada!!!",
    "Toni 99 Kapolres Jakarta timur",
    "Koboy junior", 
    "Badak Jawa bercula dua", 
    "Menyapu halaman",
    "Absen yang baru bangun tidur",
    "Pak Ajat jemur kasur",
    "mbeeeeee🐑",
    "mandi bareng🥵",
    "jasa pembersih silit dr devun awor awor mantap",
    "detik detik dapa kecelakaan",
    "kukuruyuk",
    "Rio histeris dapat hadiah sepeda",
    "radit tak tahan kuasa",
    "sakratul maut",
    "tetap sabar😇",
    "fu'ad 12 nyapu di kebun raya bogor",
    "Hore hore",
    "rafly recing mandalika",
    "fuad racing mandalika",
    "riko racing mandalika",
    "fuad terjangkit firus korona",
    "ranjang pak Abdul gusruk gusruk",
    "Buaya putih sungai musi",
    "renang",
    "mukbang",
    "mumet ndasku",
    "roti o stasiun Lempuyangan",
    "gak gitu juga bambang",
    "capek wak😭",
    "rafi tidur bareng ketos",
    "alex gembira ml nya victory",
    "radit 007 disunat bapaknya karna ketauan nonton porno anak kecil",
    "tolong saya di sekap",
    "salam kenal aku raja iblis",
    "meldino atlet basket",
    "tegar boxing",
    "iya putih",
    "ampun josep",
    "ayo kita mabar ff",
    "sirkel bersatu",
    "ayo join sirkel kita",
    "ngawi musical djindo ful bas",
    "Jawir ni bos",
    "sampe bawah👇😝",
    "kevin 08 malang ngokop silit",
    "Ahmad si niga sialan", 
    "berikan uang mu atau ku temb*k pant4t mu",
    "Buah salak asli Ngawi", 
    "harta atau nyawa",
    "kevin malang",
    "gempa bumi",
    "waduh😂😂",
    "miaw😺",
    "Sudah saya skrinsut kelakuanmu",
    "persahabatan",
    "Kita bekawan",
    "selamat datang di grup homok",
    "Pemuja setan",
    "mas Azka ambalabom",
    "sarapan",
    "apa coba",
    "Sempol kfc",
    "detik detik pria ini bertemu sahabat lama",
    "Randi 63 menjiwai bakatnya",
    "Rann utiwi bantai presiden ukraina*ngendap² dulu ga sih 😂",
    "Surya fahmi",
    "Satria coli di dalam gedung BUMN",
    "Tarian jongkok khas jogja",
    "Mas diva goyang bandung",
    "Fuad coli depan kantor kominpo", 
    "Randi cepat tidur esok sekolah"
]